title: Grierson Blog
baseurl: ""
url: ""
github_username:  grierson

plugins:
  - jekyll-feed

keep_files:
- images
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: /images
    source-highlighter: pygments
    pygments-css: style
    icons: font
