= WIP Domain Driven Design
:page-layout: post
:page-category: simple
:revdate: 2024-01-03

== Strategic design

[quote, Alberto Brandolini]
It is not the domain experts knowledge that goes into production, it is the assumption of the developers that goes into production.

Design your system and language based of the domain.

Avoid playing the telephone game by ensuring domain experts are part of the design process.

=== Bounded context and Ubiquitous language

[quote, Bound definition, Etymology Online]
"to form the boundary of," also "to set the boundaries of, confine within limits;

[quote, Context definition, Etymology Online]
"a composition, a chronicle, the entire text of a writing," from Latin contextus "a joining together,"
originally past participle of contexere "to weave together,"
from assimilated form of com "with,
together" (see con-) + texere "to weave, to make" (from PIE root *teks- "to weave,"
also "to fabricate").

A `Bounded Context` is grouping of related concepts, roles, rules, and terms that share the same context, much like `High Cohesion`.
A department (HR, Sales, Warehouse) within a business is a simplistic example of a bounded context.
They have their own language and rules that are specific to their context.

Ubiquitous language::

[quote, Ubiquitous definition, Etymology Online]
"being, existing, or turning up everywhere,"

The term "order" may be used throughout a business but it's meaning differs per department.

* A customer place's an "order" for a product
* A warehouse "order's" more stock
* Customer service department "order" a refund
* etc..

[mermaid]
----
flowchart TB
    subgraph Store
      o1[Order]
    end

    subgraph Warehouse
      o2[Order]
    end

    subgraph CustomerService["Customer Service"]
      o3[Order]
    end
----

Each of these "orders" are different from one another and handled differently.
To prevent misunderstandings when taking about "orders" create a `Ubiquitous Language` (glossary) per bounded context that gives a specific defintion per context.
Also ensure that the same `Ubiquitous language` is used by everyone throughout the project lifecycle from design to implementation.

=== Sub domains

Not all domains are equal. Some are more important than others.

Core subdomain::
A problem that justifies writing custom software rather than buying off the shelf or outsourcing.
This is the main focus of the business.

* Apple: Computers
* Barbers: Haircuts
* Netflix: Video Streaming
* Starbucks: Coffee
* etc..

Supporting subdomain::

A problem that is not the main focus of the business but still needs to be solved.
Integrating with another service for example, you need to interact with their domain but setting up the infrastructure to do so is not the main focus of the business.

Generic domain::

Things that are common to all businesses.
Solutions are available off the shelf or can be outsourced.

* Invoicing
* Accounting

=== Context map

The relationships between bounded contexts.

Conformist::
[mermaid]
----
flowchart LR
  Upstream --> Downstream
----
A bounded context that conforms to another bounded context.
So a supplier/consumer (upstream/downstream) relationship where the downstream is dependent on the upstream.
If the upstream changes the downstream needs to change as well.

Open host service::
A service that exposes it's domain to other bounded contexts

Anti-corruption layer::
[mermaid]
----
flowchart LR
    subgraph Downstream
      ACL[Anti-corruption Layer] --> Downstream
    end
  Upstream --> ACL
----

A translation layer between contexts so prevent Upstream concepts leaking into Downstream contexts.

== WIP: Tactical design

Tactical design is the implementation of the strategic design.

* Domain Events
** Facts / Things that happen in the domain
** link:https://www.eventstorming.com[Event Storming]
* Entity
** Uniquely identifiable
* Value object
** Structual equality
* Aggregate
** A transactional boundary for a grouping of associated entites and value objects to ensure consistency.
* Anti-corruption layer
** Translation between boundaries
