= WIP Domain Driven Design
:page-layout: post
:page-category: simple
:revdate: 2024-01-03

== Strategic design

Design and language based on the domain not technology.

[quote, Alberto Brandolini]
It is not the domain experts knowledge that goes into production, it is the assumption of the developers that goes into production.

Avoid playing the telephone game by ensuring domain experts are part of the design.

Hours of planning will save you days of coding.

=== Bounded context and Ubiquitous language

Bounded Context::
[quote, Bound definition, Etymology Online]
"to form the boundary of," also "to set the boundaries of, confine within limits;

[quote, Context definition, Etymology Online]
"a composition, a chronicle, the entire text of a writing," from Latin contextus "a joining together,"
originally past participle of contexere "to weave together,"
from assimilated form of com "with,
together" (see con-) + texere "to weave, to make" (from PIE root *teks- "to weave,"
also "to fabricate").

A grouping of related concepts, roles, rules, and terms that share the same context.
A department within a business is a simplistic example of a bounded context.

Ubiquitous language::

[quote, Ubiquitous definition, Etymology Online]
"being, existing, or turning up everywhere,"

The term "order" may be used throughout a business but it's meaning differs per department.

* A customer place's an "order" for a product
* A warehouse "order's" more stock
* Customer service department "order" a refund
* etc..

[mermaid]
----
flowchart TB
    subgraph Store
      o1[Order]
    end

    subgraph Warehouse
      o2[Order]
    end

    subgraph CustomerService["Customer Service"]
      o3[Order]
    end
----

Each of these "orders" are different from one another and handled differently.
To prevent misunderstandings when taking about "orders" create a `Ubiquitous Language` (glossary) per bounded context that gives a specific defintion per context.
Also ensure that the same `Ubiquitous language` is used by everyone throughout the project lifecycle from design to implementation.

=== WIP: Context map

Map of relationships between bounded contexts

* Open host service
** A service that exposes it's domain to other bounded contexts
* Conformist
** A bounded context that conforms to another bounded context
* Anti-corruption layer
** Translation between boundaries

=== Sub domains

Core subdomain::
A problem that justifies writing custom software rather than buying off the shelf or outsourcing.
This is the main focus of the business.

* Apple: Computers
* Barbers: Haircuts
* Netflix: Video Streaming
* Starbucks: Coffee
* etc..

Supporting subdomain::

A problem that is not the main focus of the business but still needs to be solved.

Generic domain::

Things that are common to all businesses.
Solutions are available off the shelf or can be outsourced.

* Invoicing
* Accounting

== WIP: Tactical design

Tactical design is the implementation of the strategic design.

* Domain Events
** Facts / Things that happen in the domain
** link:https://www.eventstorming.com[Event Storming]
* Entity
** Uniquely identifiable
* Value object
** Structual equality
* Aggregate
** A transactional boundary for a grouping of associated entites and value objects to ensure consistency.
* Anti-corruption layer
** Translation between boundaries
